name: Convert OpenAPI3 to Swagger2 in main

on:
  workflow_dispatch:  # 手動実行

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  convert_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # node_modulesのインストールをキャッシュする
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      # 必要な依存関係をインストール
      - name: Install dependencies
        run: npm ci

      # OpenAPI3仕様ドキュメントをフラット化
      - name: Flatten the OpenAPI3 document
        run: npx openapi-flattener -s api/main/openapi.yaml -o api/main/openapi_flat_31.yaml

      # OpenAPI 3.1.0 を OpenAPI 3.0.x に変換 (ダウングレード)
      - name: Convert OpenAPI3.1.0 to OpenAPI3.0.x
        run: npx openapi-downgrade api/main/openapi_flat_31.yaml -o api/main/openapi_flat_30.yaml
      
      # OpenAPI3からSwagger2へ変換
      - name: Convert OpenAPI3 to Swagger2
        run: npx api-spec-converter --from=openapi_3 --to=swagger_2 --syntax=yaml api/main/openapi_flat_30.yaml > api/main/swagger.yaml

      # 変換したファイルをコミットしてプッシュ
      - name: Commit and Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add api/main/swagger.yaml
          git commit -m "Convert OpenAPI3 to Swagger2" || echo "No changes to commit"
          git push origin main

      
