name: Create Release Directory

on:
  create:
    # ブランチが作成されたときにトリガー
    branches:
      - release/*

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  copy_and_push_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      # 新しいブランチ名を取得
      - name: Extract branch name
        id: branch_name
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # 新しいディレクトリを作成してファイルをコピー
      - name: Copy api/main to new release directory
        run: |
          NEW_DIR="api/${{ env.branch_name }}"
          cp -r api/main "$NEW_DIR"
          cp -r aw/api/main/ aw/api/

      # 必要なファイルが正しくコピーされているか確認
      - name: List files in new directory
        run: ls -al "api/${{ env.branch_name }}"
      
      # 新しいディレクトリをコミットしてmainブランチにプッシュ
      - name: Commit and push new release directory to main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "api/"
          git commit -m "Add API documentation for release ${{ env.branch_name }}"
          git push origin main
