name: Deploy Swagger UI to Pages

# openapi3→swagger2の変換後に実行
on:
  workflow_run:
    workflows: [Convert OpenAPI3 to Swagger2]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # APIドキュメントをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: contents

      # 新しいディレクトリを作成してファイルをコピー
      - name: Create and copy to new release directory in contents
        run: |
          NEW_DIR="./contents/api/${{ env.branch_name }}"
          mkdir -p "$NEW_DIR"  # コピー先ディレクトリを作成
          cp -r api/main/* "$NEW_DIR"
      
      # Swagger-UIファイルをチェックアウトして必要なものをコピー
      - name: Checkout swagger-ui
        uses: actions/checkout@v4
        with:
          repository: swagger-api/swagger-ui
          ref: 'v4.15.5'
          path: swagger-ui
          sparse-checkout: dist
      - name: Inject Swagger static files
        run: cp -n ./swagger-ui/dist/* ./contents/api/main

      # GitHub Pages用にマニュアルをビルドしてデプロイ
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./contents/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
