name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチが更新されたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 必要であれば Node.js や Python をセットアップ (Swagger 用ツールなどを利用する場合)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # デプロイするためのディレクトリを準備 (api配下のすべてのディレクトリを処理)
      - name: Prepare deployment
        run: |
          mkdir -p output
          for dir in api/*; do
            if [ -d "$dir" ]; then
              mkdir -p "output/$dir"
              cp -r "$dir"/* "output/$dir/"
            fi
          done

      # GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
